### ISSUE TITLE
Epsilon greedy strategy not working?

### ISSUE THREAD

**Issue by dgilperez** [bmuller/bandit#8]
Hi!

I configured bandit in my production stack, just following the configuration defaults (epsilon_greedy with epsilon: 0.1). I'm using bandit_choose / bandit_convert! methods for alternatives and tracking. After some time, I'm seeing that only one alternative is been shown to the users. Development stack seems to work properly (round_robin strategy).

Short term solution looks simple: switch to round_robin :) But I'd like to know if I missed something in my config or let you know just in case we can track down any bad behaviour with epsilon_greedy.

My bandit.yml below: 

```
default: &DEFAULTS
  player: round_robin
  storage: dalli

development:
  <<: *DEFAULTS

staging:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS
  player: epsilon_greedy
  player_config:
    epsilon: 0.1
```

Regards!
